### ISSUE TITLE
매칭중 시간이 페이지 켜는 시간부터 시작됨

### ISSUE THREAD

**Issue by SOONG-E** [42-Jolly-pingpong/front-end#10]
게임 시작 누른 후가 아닌 페이지에 들어서는 순간부터 타이머가 시작됩니다.

**Comment by ebcode2021** [comment]
현재 daisyUI로 구현된 모달을 flowbite로 구현예정이므로 issue 판 이후에 새로 생성하도록 하겠습니다.
