### ISSUE TITLE
window.checkPasswordModal.showModal is not a function TypeError: window.checkPasswordModal.showModal is not a function

### ISSUE THREAD

**Issue by SOONG-E** [42-Jolly-pingpong/front-end#11]
```
const ChatroomElement = (props: { chatroom: Chatroom, isOpened?: boolean }) => {
	const [currChatroom, setCurrChatroom] = useRecoilState(chatroomState);
	const [currChat, setCurrChat] = useRecoilState(chatState);
	
	const {chatroom, isOpened} = props;
	const owner = chatroom.owner; // 임시
	
	const onClickChatroom = () => {
		if (isOpened){
			window.checkPasswordModal.showModal();
		}
		setCurrChatroom(chatroom);
		setCurrChat(ChatStatus.INCHAT);
	}

	return (
		<div className="flex items-center m-1 justify-between" >
			<div className="flex items-center justify-start">
				<div className="flex items-center justify-start" onClick={onClickChatroom}>
					<img src={owner.avatarPath} className="rounded-full layout-icon w-12 h-12 mr-3"/>
					<div className="mr-2">
						{chatroom.title}
					</div>
				</div>
				<CheckPasswordModal />
				<ChatroomInfo {...chatroom}/>
			</div>
		</div>
	);
}

```

```
const CheckPasswordModal = () => {
	const [password, setPassword] = useState('');
	
	return (
		<dialog id="checkPasswordModal" className="modal">
			<form method="dialog" className="modal-box">
				<h3>Password</h3>
				<PasswordUnshown setPassword={setPassword} />
			</form>
		</dialog>
	);
}
```

이런 코드입니다 ㅠ_ㅠ

```
declare global {
	interface Window {
		modal: any;
		winRateModal: any;
		gameWaitModal: any;
		gameResultModal: any;
		twoFactorAuthCheckModal: any;
		twoFactorAuthModal: any;
		emailAuthModal: any;
		withdrawModal: any;
		avatarChangeModal: any;
		checkPasswordModal: any;
	}
}
```

여기에도 추가했어요...

아마 
ChatroomElement에 문제가 있는 것 같습니다.. return 값을 되는 다른 코드로 교체해보니 됐어요.. 하지만 모달만 교체한 경우에는 같은 문제가 발생했습니다 ㅠㅠ help me~

**Comment by ebcode2021** [comment]
git pull 해서 코드 확인했는데, CheckPasswordModal이 없네요.
다음부터는 올려주신 코드도 남겨주세요!ㅎㅅㅎ

CheckPasswordModal 밑에 export default CheckPasswordModal; 부분이 없는데 선언하셨나요??

**Comment by SOONG-E** [comment]
에러나는 코드라 깃에 안올렸습니다.. 선언했어요! 거기서 나는 에러는 아닌 것 같아요 흑흑

**Comment by ebcode2021** [comment]
`
const ChatroomElement = (props: { chatroom: Chatroom, isOpened?: boolean }) => {
	const [currChatroom, setCurrChatroom] = useRecoilState(chatroomState);
	const [currChat, setCurrChat] = useRecoilState(chatState);
	
	const {chatroom, isOpened} = props;
	const owner = chatroom.owner; // 임시
	
	const onClickChatroom = () => {
		if (isOpened){
			window.checkPasswordModal.showModal();
		}
		setCurrChatroom(chatroom);
		setCurrChat(ChatStatus.INCHAT);
	}

	return (
		<div className="flex items-center m-1 justify-between" >
			<div className="flex items-center justify-start">
				<div className="flex items-center justify-start" onClick={onClickChatroom}>
					<img src={owner.avatarPath} className="rounded-full layout-icon w-12 h-12 mr-3"/>
					<div className="mr-2">
						{chatroom.title}
					</div>
				</div>
				<CheckPasswordModal />
				<ChatroomInfo {...chatroom}/>
			</div>
		</div>
	);
}
`

여기서 <CheckPasswordModal/> 잠깐 주석하더라도 동일 에러 발생하나요??

**Comment by SOONG-E** [comment]
어디를 주석하라는 거죠??

**Comment by ebcode2021** [comment]
아 글 수정하다가 같이 삭제됬네요. <CheckPasswordModal /> return에 있는 부분이요.

**Comment by SOONG-E** [comment]
다이알로그가 2번 이상 생성돼서 생기는 에러였습니다!
