### ISSUE TITLE
[comp] 매칭 큐

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#118]
## 📢 Description

게임 모드를 선택하고 게임 시작을 누른 뒤 해당 모달이 표시됩니다.

59초까지만 큐에 대기합니다. 그 이상이 지나면 다른 사용자가 없기 때문에 자동으로 큐에서 나갑니다.
1분 동안 기다려도 대전자가 없으면 상단에 취소 안내 배너가 뜹니다.

## 🧩 Features

- [x] #119
- [x] #120

**Comment by ebcode2021** [comment]
구현 완료했습니다.
