### ISSUE TITLE
[feat] manage-chatroom view

### ISSUE THREAD

**Issue by SOONG-E** [42-Jolly-pingpong/front-end#35]
## 📢 Description

챗룸 관리하는 화면 구현하려합니다 ~_ ~

## 💎 Requirements

챗룸 안에 관리화면으로 가는 버튼이 있습니다.
관리 화면으로 들어가면 채팅방 역할에 따라 다른 화면이 나옵니다.

## ✨ Todo

- [ ] 접근 권한 확인
- [ ]

**Comment by get6** [comment]
유정님 이거 어느 view에 들어갈지 이야기해봐요~
