### ISSUE TITLE
[comp] 텍스트 애니메이션

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#54]
## 📢 Description

첫 방문한 사람이 우리 트센을 봤을 때 어떤 느낌을 줄지 고민을 해봤을 때, 웹을 쫌 많이 공부한 느낌을 주는 것이 좋을 것 같다는 생각이 들었습니다.
그래서 텍스트에 이미지를 삽입해 보여주면 초기화면이 단순해보이지만 시각적으로 영향이 클 것 같았습니다.

구현을 위해서 참고해야 할 링크입니다.
[33 Animated Backgrounds Examples](https://alvarotrigo.com/blog/animated-backgrounds-css/)에서 9번 보시면 됩니다.

## 🧩 Features

- [x] #56

**Comment by ebcode2021** [comment]
컴포넌트 만들었습니다!
