### ISSUE TITLE
[feat] 웰컴 텍스트 CSS 처리

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#56]
## 📢 Description

JOLLYPINGPONG 이라는 굵은 텍스트 안에 죠리퐁 이미지가 움직입니다.

## 💎 Requirements

알려드린 링크에 구현 방법이 나와있습니다.
저희는 tailwind를 사용하고 있어서 CSS 충돌이 날 수 있기 때문에 제공된 모든 CSS를 활용할 필요는 없어보입니다. ex) body
div와 h1 영역을 Container나 Typography로 사용해도 무방합니다.

## ✨ Todo

- [ ]
- [ ]

**Comment by ebcode2021** [comment]
텍스트 에니메이션 구현 완료했습니다.
특이점은 애니메이션이 상하로만 동작합니다.
추후 시간이 남으면 다양한 방향으로 움직이도록 애니메이션을 수정해볼게요! 일단은 완성!
