### ISSUE TITLE
[feat] Login processing

### ISSUE THREAD

**Issue by ebcode2021** [42-Jolly-pingpong/front-end#57]
## 📢 Description

42 인트라를 통해 데이터를 받은 뒤, User DB에 회원가입된 사용자의 데이터를 JWT와 함께 백엔드에서 받아옵니다.
프론트는 데이터를 확인하고 user를 state로 관리하고 #47 페이지로 이동시킵니다.

현재 user 데이터는 GetUserInfo() 라는 함수를 호출해서 임의의 목업 데이터로 화면을 렌더링 하고 있습니다.
이제 백엔드 서버에서 API를 호출해 user를 state로 관리하려고 합니다.

## 💎 Requirements

로그인 사용자는 accessToken을 보유하고 있어야 합니다.
새로고침되어도 로그인된 사용자의 데이터를 보유하고 있어야 합니다.

**Comment by get6** [comment]
이거 이름 수정하고 component와 연결하겠습니다!

**Comment by ebcode2021** [comment]
기능 구현 완료했습니다.
