### ISSUE TITLE
[comp] 42 인트라 로그인

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#58]
## 📢 Description

#43 에서 **"42 계정으로 로그인"** 버튼을 선택한 경우 42 OAuth API를 시작합니다.
42 OAuth가 정상적으로 승인(Authorize)되었을 경우, 백엔드로 리디렉션됩니다.

백엔드에서 넘어온 데이터를 User DB에 들어있는지 확인합니다.
만약 해당 인트라 ID나 email로 가입한 적이 없다면 해당 42 사용자를 회원가입 해야되는 경우로 판단합니다.
이 경우 회원가입 페이지로 이동됩니다.

데이터가 조회되는 경우 우리 서비스에 회원가입된 사용자로 판단하고 로그인 처리 후 main 페이지로 이동됩니다.

## 🧩 Features

- [x] #57 (인트라 로그인 이후 회원가입한 이력이 있는 사용자)
- [x] #64 (회원가입한 이력이 없는 사용자)

**Comment by ebcode2021** [comment]
기능 구현 완료했습니다.
