### ISSUE TITLE
[view] 42 OAuth

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#59]
## 📢 Description

해당 화면은 #43 에서 42 계정 로그인 버튼을 선택하면 넘어옵니다.
이 부분은 저희가 제어하지 않고 42에게 맡깁니다.

해당 페이지를 활성화 하기 위해선 [42's API guides](https://api.intra.42.fr/apidoc/guides/getting_started)를 참고하시길 바랍니다.

리디렉션 되면서 데이터가 넘어올 때, 데이터를 식별해 회원가입 여부를 확인합니다.
회원 정보가 있다면 이미 회원가입한 사용자로 인식 후 메인으로 이동, 없다면 회원가입 화면으로 이동해 이후 절차를 진행합니다.

## 🖼️ Components

- [x] #58

**Comment by ebcode2021** [comment]
구현 완료 했습니다.
