### ISSUE TITLE
[feat] Sign up user

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#64]
## 📢 Description

#62 이 정상적으로 수행하고 생성 버튼을 클릭하면 사용자 정보를 User DB에 저장합니다.
저장이 완료된 이후 로그인 된 것처럼 필요한 정보와 jwt를 응답 데이터로 보냅니다.
이후 #47  페이지로 리디렉션 됩니다.

## 💎 Requirements

flowbite-react의 [Button](https://www.flowbite-react.com/docs/components/button#default-buttons)을 사용합니다.

프론트엔드에서 사용자 정보를 받고난 뒤, 유효시간이 유지되는 한 새로고침을 해도 사용자 데이터를 갖고 있어야 합니다.

## ✨ Todo

- [ ]
- [ ]

**Comment by ebcode2021** [comment]
기능 구현하였습니다.
