### ISSUE TITLE
[comp] 채팅 입력

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#87]
## 📢 Description

슬랙 채팅과 비슷하지만 여러 기능을 제외한채 텍스트만 전송합니다.

HTML 문법으로 보내도 텍스트로 표현되어야 합니다.
enter를 누르면 메세지가 전송됩니다.
shift + enter를 누르면 다음 줄로 넘어갑니다.

입력이 있기 전까지 전송 버튼이 활성화되지 않고 disabled 상태로 있어야 합니다.

## 🧩 Features

- [x] #89

**Comment by SOONG-E** [comment]
HTML 문법으로 보내도 텍스트로 표현되어야 합니다.

이거 예시 들어주실 수 있나열?
